### ISSUE TITLE
Major flaw discounting survivorship bias

### ISSUE THREAD

**Issue by dfehling** [nsram/bellwethers-2020#1]
Using your dataset, the following counties correctly predicted the president in each election between year and 2000:
| Year | Num Counties correct | Percent |
| 2000 | 664 | 68.6% |
| 2004 | 647 | 97.4% |
| 2008 | 133 | 20.6% |
| 2012 | 76 | 57.1% |
| 2016 | 24 | 31.6% |
| 2020 | 4 | 16.7% |

So, the current bellwether results are inline with other times the presidency has changed parties. Please correct or add a note clarifying.

**Comment by nsram** [comment]
The selection of bellwethers in this case was based on 2 factors
1. Reasonably populated counties. At least 100,000 or more cumulative across 5 elections
2. Perfect (100%) prediction for 2000-2016. Five Recent cycles. 
3. The above two criteria mitigate against survivorship bias to a large extent (but not completely).
4. Only 24 counties survived the two criteria.  These were used as signals in 2020. Trump got 20 / 24 of counties. Biden got 4 / 24 of these counties.
5. The way you did the analysis (just using one year alone and not using population size filters) guarantees bias.

Finally, once (if ever) I get data from 1948 onwards. I can do the exact same procedure (use 5 consecutive elections to construct bellwethers to predict the sixth.  This way, I get many independent tests of the objectivity of the procedure.  It could fail in 1960 (Kennedy v Nixon) and 2000 (Bush v Gore) but the failure will not be as dramatic as in 2020.  In these close races, I expect a much more even split of the bellwether counties. Thanks for your comment. It allowed me to clarify the issue of survivorship bias (which is real and affects stocks, hedge funds etc) as it pertains to the analysis I DID. Not some other analysis.

**Comment by dfehling** [comment]
I'm sorry, but I don't quite follow. The survivorship bias is strictly due to 2. By only looking at counties which have been right 5/5 you are selecting only the survivors. What about looking at counties that got 4/5 right?

I agree that the rolling window that you suggest will help with this, which is actually what my approach demonstrates. I did NOT only look at one year.

For 2000, the window would have been 1984-2000, so I took just the data you had which was 2000. For 2004, the window would have been 1988-2004, so I took 2000 and 2004. Yes this is not perfect, but for each of the years I listed, I repeated your exact analysis but with days from 2000-that date.

So in the 2008 election where the presidency changed parties, only 133 counties that had gotten 2000 and 2004 correct were right about the 2008 presidential election. This means that only 20% of the counties that had previously been considered bellwethers were correct in that election.

One final point, I repeated your exact analysis with population filters and everything. The only difference is that I did it 5 times with a different end year each time. This is effectively assuming that the years that you don't have the data for had 100% accuracy, which while not true, still allows my analysis to point out the significant flaw in yours. 

No matter how you spin it, only 133 counties of the roughly 600 who had been right about 2000 and 2004 were right in 2008. Nothing more definitive can be said without pre 2000 data, but it still shows there can be massive extinction events for bellwether counties.

**Comment by nsram** [comment]
The strictness of the filter will matters with respect to extinction %. Hence 5-election span and population filter. I'm not sure where you got county level data prior to 2000.  No open source, unless you are part of universities subscription to Dave Leip. If someone in a university can provide me county level data (ideally going back to 1940), I can rerun the procedure for each sliding window (adjusted for overall population, so 100k now might be 60k or less then) and see where the chips fall. Other than 1960 and 2000 I do not expect massive extinction level events.  No way to tell without data. I did not use 4/5 counties because that complicates the analysis and there are no rigorous ways of combining them save for regularized models like Random Forest etc (there you would be predicting margins).  Once I get the data, I will be glad to collaborate, if you are an academic who publishes.
